import { defineRouteMiddleware } from "@astrojs/starlight/route-data";
import type { StarlightRouteData } from "@astrojs/starlight/route-data";
import { getEntry } from "astro:content";

type SidebarEntry = StarlightRouteData["sidebar"][number];

/**
 * Name each autogenerated sidebar subgroup after its directory's index page.
 *
 * Starlight labels a subdirectory's group with the directory name as it is
 * spelled on disk, so `meta/reference/glossary/` would read `glossary` beside
 * groups a person named. A directory with an index page is named by that
 * page's `title` instead, and the index page's own link keeps its
 * `sidebar.label`. A directory without one keeps Starlight's label.
 */
export const onRequest = defineRouteMiddleware(async (context) => {
  await nameGroups(context.locals.starlightRoute.sidebar);
});

async function nameGroups(entries: SidebarEntry[]): Promise<void> {
  for (const entry of entries) {
    if (entry.type !== "group") continue;
    await nameGroups(entry.entries);
    // Only groups built from a directory. A group written in
    // astro.config.mjs already carries the label its author chose.
    if (!("autogenerate" in entry)) continue;
    const suffix = `/${entry.label}/`;
    const index = entry.entries.find(
      (child) => child.type === "link" && child.href.endsWith(suffix),
    );
    if (index?.type !== "link") continue;
    const id = index.href
      .slice(import.meta.env.BASE_URL.length)
      .replace(/^\/+|\/+$/g, "");
    const page = await getEntry("docs", id);
    if (page) entry.label = page.data.title;
  }
}
