/**
 * `term write -f vale`: a `Terms` style written into a Vale styles directory
 * (proposal 0052 § 6). The golden files are the shapes a real Vale 3.20.0 run
 * produced the right findings with.
 */
import { join, resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import { describe, expect, it } from "vitest";
import { writerFor } from "../../src/term/core/writers/index.js";
import { INTERCHANGE_WRITERS } from "../../src/term/core/writers/interchange.js";
import { TermError } from "../../src/term/errors.js";
import type { Term, TermRender, TermWriter } from "../../src/term/types.js";
import { fixtureTerms, golden, term } from "./writer-fixture.js";

const STYLES = resolve("styles");
const TERMS = join(STYLES, "Terms");
const MARKER = "# Generated by manni term write. Edit the terms, not this file.";

function vale(): TermWriter {
  const found = writerFor("vale", INTERCHANGE_WRITERS);
  if (found === undefined) throw new Error("no vale writer");
  return found;
}

function render(terms: readonly Term[], existing: Record<string, string> = {}): TermRender {
  return vale().render(terms, { path: STYLES, shape: "directory" }, { existing: new Map(Object.entries(existing)) });
}

function byName(result: TermRender): Record<string, string> {
  return Object.fromEntries(result.files.map((f) => [f.path.slice(TERMS.length + 1), f.content]));
}

/** The `swap` keys of a substitution file, and whether it sets `nonword`. */
function swapsOf(content: string): { nonword: boolean; keys: string[] } {
  const parsed: unknown = parseYaml(content);
  if (typeof parsed !== "object" || parsed === null) throw new Error("not a mapping");
  const rule = parsed as { nonword?: unknown; swap?: unknown };
  const swap = typeof rule.swap === "object" && rule.swap !== null ? rule.swap : {};
  return { nonword: rule.nonword === true, keys: Object.keys(swap) };
}

describe("vale writer", () => {
  // Vale wraps a key in `\b…\b` unless `nonword` is set, and Go's `\b` only
  // knows ASCII word characters, so a term ending in a symbol (`C++`) or a
  // non-ASCII letter (`Café`) never matched. A real Vale 3.20.0 run found
  // `c++` unflagged; with computed edges it flags `c++` and leaves `c++x` and
  // `kubernetesish` alone.
  it("writes each swap key's own word boundaries, and sets nonword", () => {
    const files = byName(
      render([
        term("cpp", { label: "C++" }),
        term("kubernetes", { label: "Kubernetes", "hidden-labels": ["Kubernates"] }),
        term("cafe", { label: "Café" }),
        term("progressive-lens", { label: "progressive lens" }),
        term("dotnet", { label: ".Net" }),
      ]),
    );
    const casing = swapsOf(files["Casing.yml"] ?? "");
    expect(casing.nonword).toBe(true);
    expect(casing.keys).toEqual(["\\bc\\+\\+\\B", "\\bkubernetes\\b", "\\bcafé\\B", "\\B\\.net\\b"]);
    const lowercase = swapsOf(files["Lowercase.yml"] ?? "");
    expect(lowercase.nonword).toBe(true);
    expect(lowercase.keys).toEqual(["\\bprogressive lens\\b"]);
    const deprecated = swapsOf(files["Deprecated.yml"] ?? "");
    expect(deprecated.nonword).toBe(true);
    expect(deprecated.keys).toEqual(["\\bKubernates\\b"]);
  });

  it("holds labels, alt-labels and hidden-labels", () => {
    expect(vale().holds("directory")).toEqual(["label", "alt-labels", "hidden-labels"]);
  });

  it("renders the golden style", () => {
    const result = render(fixtureTerms());
    expect(result.files.map((f) => f.path)).toEqual(
      ["Casing.yml", "Lowercase.yml", "Deprecated.yml", "PAL.yml", "CPP.yml"].map((n) => join(TERMS, n)),
    );
    const files = byName(result);
    for (const name of Object.keys(files)) {
      expect(files[name], name).toBe(golden("vale", "Terms", name));
    }
    expect(result.removals).toEqual([]);
  });

  it("reports every field a style cannot hold", () => {
    expect(render(fixtureTerms()).dropped).toEqual([
      { id: "progressive-lens", field: "definition" },
      { id: "progressive-lens", field: "abstract" },
      { id: "progressive-lens", field: "broader" },
      { id: "progressive-lens", field: "related-terms" },
      { id: "progressive-lens", field: "scope-note" },
      { id: "spectacle-lens", field: "definition" },
      { id: "spectacle-lens", field: "narrower" },
      { id: "kubernetes", field: "definition" },
      { id: "kubernetes", field: "see" },
      { id: "api", field: "definition" },
      { id: "cpp", field: "definition" },
      { id: "cpp", field: "related-terms" },
      { id: "gleitsichtglas", field: "definition" },
    ]);
  });

  it("renders the same bytes twice", () => {
    expect(render(fixtureTerms())).toEqual(render(fixtureTerms()));
  });

  it("omits a file with no entries", () => {
    const files = byName(render([term("kubernetes", { label: "Kubernetes" })]));
    expect(Object.keys(files)).toEqual(["Casing.yml"]);
  });

  it("writes no casing rule for an all-caps label and no acronym rule for a label", () => {
    expect(render([term("api", { label: "API", "alt-labels": ["REST API"] })]).files).toEqual([]);
  });

  it("writes no acronym rule for an acronym that is another term's label", () => {
    const files = byName(
      render([
        term("api", { label: "API" }),
        term("interface", { label: "interface", "alt-labels": ["API"] }),
      ]),
    );
    expect(Object.keys(files)).toEqual(["Lowercase.yml"]);
  });

  it("writes one acronym file when two terms share the acronym", () => {
    const result = render([
      term("progressive-lens", { label: "progressive lens", "alt-labels": ["PAL"] }),
      term("phase-alternating-line", { label: "phase alternating line", "alt-labels": ["PAL"] }),
    ]);
    const pal = result.files.filter((f) => f.path === join(TERMS, "PAL.yml"));
    expect(pal).toHaveLength(1);
    expect(pal[0]?.content).toContain("'progressive lens (PAL)'");
  });

  it("quotes a key or value YAML would misread, and escapes regex metacharacters", () => {
    const files = byName(render([term("yes", { label: "yes" }), term("net", { label: ".NET: Core" })]));
    // A bounded key is never a bare YAML boolean; its value still needs quotes.
    expect(files["Lowercase.yml"]).toContain('  \\byes\\b: "[Yy]es"\n');
    expect(files["Casing.yml"]).toContain('  "\\\\B\\\\.net: core\\\\b": "\\\\.NET: Core"\n');
  });

  it("removes a marked file the set no longer produces", () => {
    const stale = join(TERMS, "OLD.yml");
    const result = render(fixtureTerms(), {
      [stale]: `${MARKER}\nextends: conditional\n`,
      [join(TERMS, "PAL.yml")]: `${MARKER}\n`,
    });
    expect(result.removals).toEqual([stale]);
  });

  it("refuses a Terms directory holding a file manni did not write", () => {
    const foreign = join(TERMS, "Mine.yml");
    expect(() => render(fixtureTerms(), { [foreign]: "extends: existence\n" })).toThrow(
      new TermError(`${foreign} was not written by manni. Move it, or pass -o <styles directory>.`),
    );
  });

  it("leaves files outside Terms alone", () => {
    const result = render(fixtureTerms(), { [join(STYLES, "Google", "Passive.yml")]: "extends: existence\n" });
    expect(result.removals).toEqual([]);
  });

  it("refuses an acronym that would replace one of its own files", () => {
    expect(() => render([term("casing", { label: "letter casing", "alt-labels": ["CASING"] })])).toThrow(
      new TermError('the acronym "CASING" would replace Terms/Casing.yml. Rename the alt-label.'),
    );
  });

  it("refuses a file shape", () => {
    expect(() => vale().render(fixtureTerms(), { path: join(STYLES, "x.yml"), shape: "file" }, { existing: new Map() })).toThrow(
      TermError,
    );
  });
});
