/**
 * `term write -f skos`: the set as a SKOS concept scheme in JSON-LD. The
 * document is the scheme, and each term is a concept at `#<id>` within it.
 *
 * A relation (`broader`, `narrower`, `related-terms`) names another term by
 * label or id, and becomes a reference to that concept. A value naming no term
 * is left out: a dangling reference is `check`'s finding, not a field this
 * format cannot hold.
 */
import type { Term, TermField, TermShape, TermWriter } from "../../types.js";
import { droppedFields, requireShape } from "./render-util.js";

const HOLDS: readonly TermField[] = [
  "label",
  "definition",
  "alt-labels",
  "hidden-labels",
  "broader",
  "narrower",
  "related-terms",
  "scope-note",
];

const CONTEXT = {
  skos: "http://www.w3.org/2004/02/skos/core#",
  dcterms: "http://purl.org/dc/terms/",
};

/** The scheme's `@id`: the document itself, which the concepts' `#<id>` fragments sit in. */
const SCHEME_ID = "";

type Literal = string | { "@value": string; "@language": string };

function literal(term: Term, value: string): Literal {
  return term.language === undefined ? value : { "@value": value, "@language": term.language };
}

/** The term a relation value names: a label first, then an id, compared case-insensitively. Never `self`. */
function resolve(terms: readonly Term[], self: Term, value: string): Term | undefined {
  const wanted = value.toLowerCase();
  const others = terms.filter((t) => t !== self);
  return (
    others.find((t) => t.record.label.toLowerCase() === wanted) ?? others.find((t) => t.id.toLowerCase() === wanted)
  );
}

function references(terms: readonly Term[], self: Term, values: readonly string[] | undefined): { "@id": string }[] {
  const ids: string[] = [];
  for (const value of values ?? []) {
    const target = resolve(terms, self, value);
    if (target !== undefined && !ids.includes(target.id)) ids.push(target.id);
  }
  return ids.map((id) => ({ "@id": `#${id}` }));
}

function concept(terms: readonly Term[], term: Term): Record<string, unknown> {
  const { record } = term;
  const node: Record<string, unknown> = {
    "@id": `#${term.id}`,
    "@type": "skos:Concept",
    "skos:inScheme": { "@id": SCHEME_ID },
    "skos:prefLabel": literal(term, record.label),
  };
  if (record["alt-labels"] !== undefined) node["skos:altLabel"] = record["alt-labels"].map((v) => literal(term, v));
  if (record["hidden-labels"] !== undefined) {
    node["skos:hiddenLabel"] = record["hidden-labels"].map((v) => literal(term, v));
  }
  if (record.definition !== undefined) node["skos:definition"] = literal(term, record.definition);
  if (record["scope-note"] !== undefined) node["skos:scopeNote"] = literal(term, record["scope-note"]);
  const relations = [
    ["skos:broader", record.broader],
    ["skos:narrower", record.narrower],
    ["skos:related", record["related-terms"]],
  ] as const;
  for (const [key, values] of relations) {
    const refs = references(terms, term, values);
    if (refs.length > 0) node[key] = refs;
  }
  return node;
}

export const skosWriter: TermWriter = {
  format: "skos",
  shapes: ["file"],
  holds: (_shape: TermShape) => HOLDS,
  render(terms, target) {
    requireShape("skos", target, "file");
    const document = {
      "@context": CONTEXT,
      "@graph": [
        {
          "@id": SCHEME_ID,
          "@type": "skos:ConceptScheme",
          "dcterms:description": "Generated by manni term write.",
        },
        ...terms.map((term) => concept(terms, term)),
      ],
    };
    const content = `${JSON.stringify(document, null, 2)}\n`;
    return { files: [{ path: target.path, content }], removals: [], dropped: droppedFields(terms, HOLDS) };
  },
};
