/**
 * `term write -f vale`: a Vale style named `Terms`, written into a styles
 * directory (proposal 0052 § 6). Every rule shape here was chosen against a
 * real Vale 3.20.0 run.
 *
 * - `Terms/Casing.yml` enforces the exact form of a title- or mixed-case
 *   designation: `Kubernetes`, `K8s`, `iPhone`.
 * - `Terms/Lowercase.yml` enforces an all-lowercase designation, allowing a
 *   capital first letter so a sentence can start with it.
 * - `Terms/Deprecated.yml` swaps each hidden-label for its term's label.
 * - `Terms/<ACRONYM>.yml` asks for an all-caps alt-label to be spelled out on
 *   first use, as `<label> (<ACRONYM>)`.
 *
 * An all-caps designation gets no casing rule: enforcing the case of `IT` fires
 * on nearly every paragraph. manni owns `Terms/`: every file opens with the
 * marker line, a file without it is someone else's and stops the write, and a
 * marked file the set no longer produces is removed.
 */
import { isAbsolute, join, relative, sep } from "node:path";
import { stringify } from "yaml";
import { TermError } from "../../errors.js";
import type { RenderedFile, TermField, TermShape, TermWriter } from "../../types.js";
import { droppedFields, requireShape } from "./render-util.js";

export const VALE_MARKER = "# Generated by manni term write. Edit the terms, not this file.";
const STYLE = "Terms";
const HOLDS: readonly TermField[] = ["label", "alt-labels", "hidden-labels"];
/** The style's own files, which an acronym file may not replace. */
const OWN_FILES = ["Casing", "Lowercase", "Deprecated"] as const;

const REGEX_METACHARACTERS = /[\\^$.|?*+()[\]{}]/g;

function escapeRegex(value: string): string {
  return value.replace(REGEX_METACHARACTERS, "\\$&");
}

/**
 * A swap value as Vale reads it. Vale matches the value as a pattern against
 * the text it found, so a value holding a metacharacter is escaped, and only
 * then: the `%s` in the message prints the value, so the escape shows in that
 * message (`Use 'C\+\+' instead of 'c++'`). An exact message is worth more for
 * the common case than for the rare one.
 */
function swapValue(value: string): string {
  return value.search(REGEX_METACHARACTERS) === -1 ? value : escapeRegex(value);
}

/**
 * A YAML scalar Vale's parser reads back as the same string. YAML 1.1 rules
 * quote `yes`, `on` and friends, which a 1.1 parser would read as booleans.
 * A line break cannot sit in a one-line key, so such a string is written as a
 * JSON string, which is valid double-quoted YAML.
 */
function scalar(value: string): string {
  if (/[\r\n]/.test(value)) return JSON.stringify(value);
  const out = stringify(value, { version: "1.1", lineWidth: 0 });
  return out.endsWith("\n") ? out.slice(0, -1) : out;
}

/** A YAML double-quoted scalar. */
function doubleQuoted(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/** A YAML single-quoted scalar, which keeps backslashes literal for a regex. */
function singleQuoted(value: string): string {
  return `'${value.replaceAll("'", "''").replaceAll(/[\r\n]+/g, " ")}'`;
}

/** Vale formats a message with Go's `fmt`, so a literal `%` is doubled. */
function messageText(value: string): string {
  return value.replaceAll("%", "%%");
}

type Casing = "none" | "all-caps" | "lowercase" | "mixed";

function casingOf(value: string): Casing {
  if (!/[\p{Lu}\p{Ll}\p{Lt}]/u.test(value)) return "none";
  const letters = value.match(/\p{L}/gu)?.length ?? 0;
  if (letters >= 2 && !/[\p{Ll}\p{Lt}]/u.test(value)) return "all-caps";
  if (!/[\p{Lu}\p{Lt}]/u.test(value)) return "lowercase";
  return "mixed";
}

/** `progressive lens` → `[Pp]rogressive lens`: the first letter may be a capital, to start a sentence. */
function sentenceStartPattern(value: string): string {
  const [first = "", ...rest] = Array.from(value);
  const upper = first.toUpperCase();
  const head = upper !== first && Array.from(upper).length === 1 ? `[${upper}${first}]` : escapeRegex(first);
  return `${head}${escapeRegex(rest.join(""))}`;
}

/** A swap list in insertion order. A key already present keeps its first value, as YAML allows one. */
class Swaps {
  private readonly entries = new Map<string, string>();
  add(key: string, value: string): void {
    if (!this.entries.has(key)) this.entries.set(key, value);
  }
  get size(): number {
    return this.entries.size;
  }
  lines(): string[] {
    return [...this.entries].map(([key, value]) => `  ${scalar(key)}: ${scalar(value)}`);
  }
}

function substitution(message: string, level: string, options: string[], swaps: Swaps): string {
  return [
    VALE_MARKER,
    "extends: substitution",
    `message: ${doubleQuoted(message)}`,
    `level: ${level}`,
    "ignorecase: true",
    ...options,
    "swap:",
    ...swaps.lines(),
  ]
    .map((line) => `${line}\n`)
    .join("");
}

function acronymRule(acronym: string, label: string): string {
  const expansion = escapeRegex(label).replaceAll(/[\r\n]+/g, " ");
  return [
    VALE_MARKER,
    "extends: conditional",
    `message: ${doubleQuoted(messageText(`Spell out '${acronym}' on first use, as '${label} (${acronym})'.`))}`,
    "level: warning",
    "ignorecase: false",
    `first: ${singleQuoted(`\\b(${escapeRegex(acronym)})\\b`)}`,
    `second: ${singleQuoted(`(?i)${expansion} \\((${escapeRegex(acronym)})\\)`)}`,
  ]
    .map((line) => `${line}\n`)
    .join("");
}

/** An acronym as a file name: anything a path or a Vale rule name cannot carry becomes `-`. */
function acronymFileName(acronym: string): string {
  return acronym.replaceAll(/[^\p{L}\p{N}_-]/gu, "-");
}

function firstLine(content: string): string {
  const end = content.search(/\r?\n/);
  return end === -1 ? content : content.slice(0, end);
}

export const valeWriter: TermWriter = {
  format: "vale",
  shapes: ["directory"],
  holds: (_shape: TermShape) => HOLDS,
  render(terms, target, context) {
    requireShape("vale", target, "directory");
    const termsDir = join(target.path, STYLE);

    // Someone else's file in Terms/ stops the write before anything is computed.
    const marked: string[] = [];
    for (const [path, content] of context.existing) {
      const rel = relative(termsDir, path);
      if (rel === "" || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) continue;
      if (firstLine(content) !== VALE_MARKER) {
        throw new TermError(`${path} was not written by manni. Move it, or pass -o <styles directory>.`);
      }
      if (!rel.includes(sep) && !rel.includes("/")) marked.push(path);
    }

    const casing = new Swaps();
    const lowercase = new Swaps();
    const deprecated = new Swaps();
    const acronyms: { name: string; content: string }[] = [];
    const labels = new Set(terms.map((t) => t.record.label));

    for (const term of terms) {
      const { label } = term.record;
      const labelIsAllCaps = casingOf(label) === "all-caps";
      for (const designation of [label, ...(term.record["alt-labels"] ?? [])]) {
        const kind = casingOf(designation);
        if (kind === "lowercase") lowercase.add(escapeRegex(designation), sentenceStartPattern(designation));
        if (kind === "mixed") casing.add(escapeRegex(designation.toLowerCase()), swapValue(designation));
        if (kind !== "all-caps" || designation === label || labelIsAllCaps || labels.has(designation)) continue;
        const name = acronymFileName(designation);
        const own = OWN_FILES.find((file) => file.toLowerCase() === name.toLowerCase());
        if (own !== undefined) {
          throw new TermError(`the acronym "${designation}" would replace Terms/${own}.yml. Rename the alt-label.`);
        }
        if (acronyms.some((a) => a.name.toLowerCase() === name.toLowerCase())) continue;
        acronyms.push({ name, content: acronymRule(designation, label) });
      }
      for (const hidden of term.record["hidden-labels"] ?? []) {
        deprecated.add(escapeRegex(hidden), swapValue(label));
      }
    }

    const files: RenderedFile[] = [];
    const add = (name: string, content: string): void => {
      files.push({ path: join(termsDir, `${name}.yml`), content });
    };
    if (casing.size > 0) {
      add("Casing", substitution("Use '%s' instead of '%s'.", "error", ["vocab: false"], casing));
    }
    if (lowercase.size > 0) {
      add(
        "Lowercase",
        substitution("Write '%[2]s' in lowercase, except to start a sentence.", "error", ["vocab: false"], lowercase),
      );
    }
    if (deprecated.size > 0) {
      add("Deprecated", substitution("Use '%s' instead of '%s'.", "warning", ["matchcase: true"], deprecated));
    }
    for (const acronym of acronyms) add(acronym.name, acronym.content);

    // Compared without case: on a case-insensitive disk `pal.yml` and `PAL.yml`
    // are one file, and removing the old name would delete the new one.
    const produced = new Set(files.map((f) => relative(termsDir, f.path).toLowerCase()));
    const removals = marked.filter((path) => !produced.has(relative(termsDir, path).toLowerCase())).sort();

    return { files, removals, dropped: droppedFields(terms, HOLDS) };
  },
};
